import { NextResponse, type NextRequest } from "next/server";
import JSZip from "jszip";
import { buildScriptPack } from "../../../../../lib/scripts/catalog";
import { getScriptStorageDriverName } from "../../../../../lib/scripts/storage";
import { SupabaseScriptFileStorage } from "../../../../../lib/scripts/storage/supabaseStorage";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(_request: NextRequest, { params }: { params: Promise<{ pack: string }> }) {
  const { pack: packSlug } = await params;
  const result = await buildScriptPack(packSlug);

  if (!result) {
    return NextResponse.json({ error: "Script pack not found." }, { status: 404 });
  }

  const zip = new JSZip();
  zip.file(`${result.pack.slug}.ps1`, result.body);
  zip.file(
    "README.md",
    `# ${result.pack.label}

Generated by OperatorOS ScriptForge for scripts.operatoros.net.

Scripts included: ${result.scripts.length}

Review each script before running in production.
`,
  );
  const zipBytes = await zip.generateAsync({ type: "uint8array" });
  const zipFileName = result.pack.fileName.replace(/\.ps1$/, ".zip");
  let storageUri: string | null = null;

  if (getScriptStorageDriverName() === "database") {
    storageUri = await new SupabaseScriptFileStorage().uploadBytes(
      `packs/${result.pack.slug}/${zipFileName}`,
      zipBytes,
      "application/zip",
    );
  }

  return new NextResponse(Buffer.from(zipBytes), {
    headers: {
      "content-type": "application/zip",
      "content-disposition": `attachment; filename="${zipFileName}"`,
      "x-scriptforge-pack-count": String(result.scripts.length),
      ...(storageUri ? { "x-scriptforge-storage-uri": storageUri } : {}),
    },
  });
}
